version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: expense
      POSTGRES_PASSWORD: expense
      POSTGRES_DB: expensedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata_expense:/var/lib/postgresql/data
volumes:
  pgdata_expense: